CREATE DATABASE IF NOT EXISTS member_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

USE member_db;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userid VARCHAR(50) NOT NULL UNIQUE,
  userpw VARCHAR(255) NOT NULL,
  username VARCHAR(100) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS board (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  content TEXT NOT NULL,
  userid VARCHAR(50) NOT NULL,
  username VARCHAR(100) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  recommend_count INT NOT NULL DEFAULT 0,
  unrecommend_count INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_board_userid
    FOREIGN KEY (userid) REFERENCES users(userid)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS board_files (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  board_id INT UNSIGNED NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  uploaded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_board_files_board
    FOREIGN KEY (board_id) REFERENCES board(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS comments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  post_id INT UNSIGNED NOT NULL,
  userid VARCHAR(50) NOT NULL,
  username VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_comments_post
    FOREIGN KEY (post_id) REFERENCES board(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS board_recommend (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  board_id INT UNSIGNED NOT NULL,
  userid VARCHAR(50) NOT NULL,
  action ENUM('recommend','unrecommend') NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_recommend_board
    FOREIGN KEY (board_id) REFERENCES board(id)
    ON DELETE CASCADE,
  CONSTRAINT fk_recommend_user
    FOREIGN KEY (userid) REFERENCES users(userid)
    ON DELETE CASCADE,
  UNIQUE KEY uq_board_user (board_id, userid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;